[package]
name = "shorty"
version = "0.1.0"
edition = "2021"
authors = ["Ryan Noronha"]
license = "MIT OR Apache-2.0"

[dependencies]
mongodb = "2.3.1"
sha2 = "0.10.6"
rand = "0.8.5"
hex = "0.4.3"
dotenv = "0.15.0"

[dependencies.tokio]
version = "1.25.0"
features = ["full"]

[dependencies.serde]
version = "1.0.152"
features = ["derive"]
