on:
  pull_request:
    branches:
      - main

    paths:
      - "**.rs"
      - "Cargo.toml"
      - "Cargo.lock"
      - "clippy.toml"
      - "rustfmt.toml"

jobs:
  lint_and_format:
    name: Lint and format check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Cache build files
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-cargo-and-target-cache-${{ hashFiles('**/Cargo.lock') }}
          path: |
            ~/.cargo
            ./target

      - name: Check for formatting issues
        run: cargo fmt --check

      - name: Check for linting issues
        run: cargo clippy -- -D warnings

  check_and_test:
    name: Check for compile errors and run tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Cache build files
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-cargo-and-target-cache-${{ hashFiles('**/Cargo.lock') }}
          path: |
            ~/.cargo
            ./target

      - name: Check for compile errors
        run: cargo check

      - name: Run doc tests
        run: cargo test --doc

      - name: Run unit tests
        run: cargo test --lib --bins
